apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapiapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapiapp
  template:
    metadata:
      labels:
        app: myapiapp
    spec:
      containers:
      - name: myapiapp
        image: <your-acr-name>.azurecr.io/myapiapp:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myapiapp-service
spec:
  type: LoadBalancer
  selector:
    app: myapiapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
