apiVersion: v1
kind: Service
metadata:
  name: myapiapp-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
spec:
  type: LoadBalancer
  selector:
    app: myapiapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
